#!/usr/bin/env node
/**
 * Audio Base64 Build Script
 * Converts audio files from assets/audio/ to Base64-encoded JavaScript module
 * for CORS-safe WebAudio in iframe environments (e.g., Blackboard Ultra)
 * 
 * Usage: node build-audio.js
 * Output: js/audio-data.js
 */

const fs = require('fs');
const path = require('path');

const AUDIO_DIR = path.join(__dirname, 'assets', 'audio');
const OUTPUT_FILE = path.join(__dirname, 'js', 'audio-data.js');

/**
 * Convert file to Base64 data URI
 * @param {string} filePath - Path to audio file
 * @returns {string} Base64 data URI
 */
function fileToBase64DataURI(filePath) {
    const fileBuffer = fs.readFileSync(filePath);
    const base64String = fileBuffer.toString('base64');
    return `data:audio/wav;base64,${base64String}`;
}

/**
 * Main build function
 */
function build() {
    console.log('[BUILD-AUDIO] Starting audio file conversion...');
    console.log(`[BUILD-AUDIO] Source directory: ${AUDIO_DIR}`);
    console.log(`[BUILD-AUDIO] Output file: ${OUTPUT_FILE}`);

    // Check if audio directory exists
    if (!fs.existsSync(AUDIO_DIR)) {
        console.error(`[BUILD-AUDIO] ERROR: Audio directory not found: ${AUDIO_DIR}`);
        process.exit(1);
    }

    // Read directory and filter for .wav files
    const files = fs.readdirSync(AUDIO_DIR)
        .filter(file => file.toLowerCase().endsWith('.wav'))
        .sort(); // Sort alphabetically for deterministic output

    if (files.length === 0) {
        console.warn('[BUILD-AUDIO] WARNING: No .wav files found in audio directory');
        console.warn(`[BUILD-AUDIO] Expected directory: ${AUDIO_DIR}`);
    }

    console.log(`[BUILD-AUDIO] Found ${files.length} audio file(s):`);
    files.forEach(file => console.log(`  - ${file}`));

    // Convert each file to Base64
    const audioData = {};
    let totalSize = 0;

    for (const file of files) {
        const filePath = path.join(AUDIO_DIR, file);
        try {
            const stats = fs.statSync(filePath);
            const dataURI = fileToBase64DataURI(filePath);
            audioData[file] = dataURI;
            totalSize += stats.size;
            console.log(`[BUILD-AUDIO] ✓ Encoded: ${file} (${(stats.size / 1024).toFixed(2)} KB)`);
        } catch (error) {
            console.error(`[BUILD-AUDIO] ERROR: Failed to encode ${file}:`, error.message);
            process.exit(1);
        }
    }

    // Generate JavaScript module
    const timestamp = new Date().toISOString();
    const moduleContent = `/**
 * Audio Data Module (Auto-generated)
 * 
 * This file is automatically generated by build-audio.js
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * Generated: ${timestamp}
 * Files: ${files.length} audio file(s)
 * Total size: ${(totalSize / 1024).toFixed(2)} KB (raw), ~${(totalSize * 1.33 / 1024).toFixed(2)} KB (Base64)
 * 
 * Contains Base64-encoded audio data URIs for CORS-safe WebAudio playback
 * in iframe environments (e.g., Blackboard Ultra).
 */

/**
 * Audio data as Base64-encoded data URIs
 * Key: filename (e.g., 'fan.wav')
 * Value: data URI (e.g., 'data:audio/wav;base64,...')
 */
const AUDIO_DATA = ${JSON.stringify(audioData, null, 2)};

// Export for use in audio.js
if (typeof window !== 'undefined') {
  window.AUDIO_DATA = AUDIO_DATA;
}

// ES6 module export (if using modules)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { AUDIO_DATA };
}
`;

    // Ensure js directory exists
    const jsDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(jsDir)) {
        fs.mkdirSync(jsDir, { recursive: true });
        console.log(`[BUILD-AUDIO] Created directory: ${jsDir}`);
    }

    // Write output file
    try {
        fs.writeFileSync(OUTPUT_FILE, moduleContent, 'utf8');
        console.log(`[BUILD-AUDIO] ✓ Generated: ${OUTPUT_FILE}`);
        console.log(`[BUILD-AUDIO] ✓ Total encoded size: ~${(totalSize * 1.33 / 1024).toFixed(2)} KB (Base64)`);
        console.log('[BUILD-AUDIO] Build complete!');
    } catch (error) {
        console.error(`[BUILD-AUDIO] ERROR: Failed to write output file:`, error.message);
        process.exit(1);
    }
}

// Run build
build();

